---
# tasks file for lighthouse-role
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  notify: Restart nginx service

- name: Get lighthouse distrib
  ansible.builtin.get_url:
    url: "{{ lighthouse_src }}"
    dest: "./lighthouse.zip"
    mode: "0644"
- name: Unarchive lighthouse distrib into nginx
  become: true
  ansible.builtin.unarchive:
    src: ./lighthouse.zip
    dest: /var/www/html/
    remote_src: true
  notify: Restart nginx service
- name: Make nginx config
  become: true
  ansible.builtin.template:
    src: lighthouse.j2
    dest: /etc/nginx/sites-enabled/default
    mode: "0644"
  notify: Restart nginx service
- name: Remove lighthouse distrib
  ansible.builtin.file:
    path: "./lighthouse.zip"
    state: absent
